language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

script:
 - vendor/bin/phpunit

before_script:
 - phpenv rehash > /dev/null
 - composer selfupdate --quiet
 - composer install --no-interaction --prefer-source --dev

notifications:
  email:
    - me@mikevanriel.com
